### ISSUE TITLE
Player navigation not working

### ISSUE THREAD

**Issue by uPagge** [TryGhost/Wave#19] opened 2022-02-02 16:10 UTC
Hello. Navigation on the podxat losing track does not work on the main page. And on the podcast page, even the display of this strip does not work, not like navigation. Is it possible to fix it?

**Comment by minimaluminium** [comment] 2022-02-21 05:28
Hey @uPagge, not sure I understand the issue well. Would you be able to elaborate on that bit more?

**Comment by uPagge** [comment] 2022-02-21 08:29
Sorry my english is not very good :)

If you start the podcast on the main page, it is not possible to jump to an arbitrary time using the progress bar. I wanted to know if it's possible to make it interactive so that you can click on the track's progress bar and navigate to that location. Now it doesn't work. Only the navigation buttons work, which allow you to scroll by 30 seconds, which is a very long time if you need to get into the middle of an hourly episode

The second problem is that on the podcast page, when playing, the progress bar does not work, it remains empty and . The problem is observed on Google Chrome and Safari

**Comment by minimaluminium** [comment] 2022-02-28 03:05
Hey again :)

1. The player supports very basic functions and has no support for this at the moment. This is expected for now, but we will consider about some updates to the theme in the future.

2. I couldn't reproduce the issue on the podcast page. Here I'm using Chrome.

https://user-images.githubusercontent.com/1418797/155917209-654d541f-4fe4-49b4-9d16-c7f8d3042e5e.mp4

**Comment by uPagge** [comment] 2022-02-28 05:57
it's weird because it doesn't work for me in chrome on macos

**Comment by minimaluminium** [comment] 2022-03-08 10:44
Same for the video above. The browser is Chrome on macOS `Version 99.0.4844.51 (Official Build) (arm64)`

**Comment by minimaluminium** [comment] 2022-03-18 03:19
Hey, I was able the reproduce this. This is now fixed.

**Closed** 2022-03-18 03:18 UTC

**Comment by uPagge** [comment] 2022-03-21 13:37
Great news
